#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;
use SetupMinil;
use File::Glob qw(bsd_glob);

for my $directory ( bsd_glob("$SetupMinil::ROOT/snapshots/*/*") ) {
    next unless -d $directory;
    check_snapshot($directory);
}
